#! /bin/sh

wmname LG3D
xsetroot -cursor_name left_ptr
pgrep -x sxhkd >/dev/null || sxhkd &
feh --randomize --bg-fill ~/dotfiles/wallpapers/1.png &
/bin/bash $HOME/.config/polybar/launch.sh &
/bin/bash $HOME/dotfiles/config/bspwm/autostart.sh &

bspc monitor -d I II III IV V

bspc config border_width 3
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
