#! /bin/sh

wmname LG3D
xsetroot -cursor_name left_ptr
pgrep -x sxhkd >/dev/null || sxhkd &
feh --randomize --bg-fill $HOME/Documents/dotfiles/wallpapers/AnimeWaiting.png &
/bin/bash $HOME/.config/polybar/launch.sh &
/bin/bash $HOME/Documents/dotfiles/config/bspwm/autostart.sh &

bspc monitor -d I II III IV V

bspc config border_width 3
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Alacritty state=floating center=on
bspc rule -a Spotify state=floating center=on desktop=^5
bspc rule -a "Clash for Windows" state=floating center=on
